server:
  port: 8080

spring:
  application:
    name: k8s-demo

# Actuator 健康检查
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
